2024-11-06 22:01:26,334 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "<string>", line 29, in test_runner
  File "/storage/emulated/0/python/module_12_4/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано list
2024-11-06 22:01:26,340 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "<string>", line 17, in test_walk
  File "/storage/emulated/0/python/module_12_4/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -2
